### ISSUE TITLE
What kind of URLs supported for radioURL()?

### ISSUE THREAD

**Issue by favianrizqulloh** [dehy/react-native-radio-player#1]
I defined the `radioURL()` with SHOUTcast URL
```js
// ...
RadioPlayer.radioURL('https://s9.viastreaming.net:17020/stream');
// ...
```

and got an error saying
`TypeError: null is not an object (evaluating '_reactNativeRadioPlayer.default.radioURL')`

**Comment by dehy** [comment]
The URL you provided works for me.

Are you on iOS or android? Which version of the lib are you using (the last one is 0.2.2)?

**Comment by favianrizqulloh** [comment]
> Are you on iOS or android? Which version of the lib are you using (the last one is 0.2.2)?

Android and I'm using the latest lib

I run the project on Expo btw, or maybe this should be meant to work on Vanilla RN?

**Comment by dehy** [comment]
As I never used Expo, I don't know how it works. But this lib is using native code for playback and I think Expo can't execute native code.

**Comment by xmasterx47** [comment]
same problem here, solved this error?

**Comment by xmasterx47** [comment]
the Android and IOS folders were missing from my project, I ran the following command: `npm execute eject`, then edited the `gradle.properties` file inside android folder and added the following line `org.gradle.jvmargs = -Xmx4608m`, when I ran the `npm run android` command and it worked perfectly
